const PREFIX = 'md-reader__'
const p = ([block]: TemplateStringsArray) => PREFIX + block

export default {
  PREFIX,
  MD_BODY: p`body`,
  MD_SIDE: p`side`,
  MD_SIDE_ACTIVE: p`side-li--active`,
  MD_CONTENT: p`markdown-content`,
  MD_BUTTON: p`btn`,
  HEAD_ANCHOR: p`head-anchor`,
  BUTTON_WRAP_ELE: p`button-wrap`,
  CODE_TOGGLE_BTN: p`btn--code-toggle`,
  SIDE_EXPAND_BTN: p`btn--side-expand`,
  GO_TOP_BTN: p`btn--go-top`,
  COPY_BTN: p`btn--copy`,
  SIDE_COLLAPSED: 'side-collapsed',
  SIDE_EXPANDED: 'side-expanded',
  FILE_TREE_PANEL: p`file-tree-side`,
  FILE_TREE_HEADER: p`file-tree-side__header`,
  FILE_TREE_SEARCH: p`file-tree-side__search`,
  FILE_TREE_CONTENT: p`file-tree-side__content`,
  FILE_TREE_TOGGLE: p`file-tree-side__toggle`,
  FILE_TREE: p`file-tree`,
  FILE_TREE_ITEM: p`file-tree__item`,
  FILE_TREE_COLLAPSED: 'file-tree-collapsed',
  HAS_FILE_TREE: 'has-file-tree',
  MODAL: p`modal`,
  ZOOM_IMAGE: p`zoom-image`,
}
